import type { OrderBookItem } from '../types/orderBook'

/** Sample order book data – replace with API response data */
export const ORDER_BOOK_COLUMNS: { key: keyof OrderBookItem; label: string }[] = [
  { key: 'orderid', label: 'Order ID' },
  { key: 'tradingsymbol', label: 'Trading Symbol' },
  { key: 'transactiontype', label: 'Type' },
  { key: 'quantity', label: 'Qty' },
  { key: 'price', label: 'Price' },
  { key: 'triggerprice', label: 'Trigger Price' },
  { key: 'averageprice', label: 'Avg Price' },
  { key: 'status', label: 'Status' },
  { key: 'orderstatus', label: 'Order Status' },
  { key: 'variety', label: 'Variety' },
  { key: 'ordertype', label: 'Order Type' },
  { key: 'producttype', label: 'Product' },
  { key: 'duration', label: 'Duration' },
  { key: 'exchange', label: 'Exchange' },
  { key: 'disclosedquantity', label: 'Disclosed Qty' },
  { key: 'squareoff', label: 'Square Off' },
  { key: 'stoploss', label: 'Stop Loss' },
  { key: 'trailingstoploss', label: 'Trailing SL' },
  { key: 'symboltoken', label: 'Symbol Token' },
  { key: 'instrumenttype', label: 'Instrument' },
  { key: 'strikeprice', label: 'Strike Price' },
  { key: 'optiontype', label: 'Option Type' },
  { key: 'expirydate', label: 'Expiry' },
  { key: 'lotsize', label: 'Lot Size' },
  { key: 'cancelsize', label: 'Cancel Size' },
  { key: 'filledshares', label: 'Filled' },
  { key: 'unfilledshares', label: 'Unfilled' },
  { key: 'text', label: 'Text' },
  { key: 'updatetime', label: 'Update Time' },
  { key: 'exchtime', label: 'Exch Time' },
  { key: 'exchorderupdatetime', label: 'Exch Order Update' },
  { key: 'fillid', label: 'Fill ID' },
  { key: 'filltime', label: 'Fill Time' },
  { key: 'parentorderid', label: 'Parent Order ID' },
  { key: 'uniqueorderid', label: 'Unique Order ID' },
  { key: 'exchangeorderid', label: 'Exchange Order ID' },
]
